"""Availability-model tests.

Training data is generated by the optical model itself, so these are genuine
end-to-end checks: if the physics and the predictive model disagree, the
calibration tests fail.
"""

import numpy as np
import pytest

from uuv_mode_aware_navigation.availability import (
    AvailabilityModel,
    AvailabilitySample,
    brier_score,
)
from uuv_mode_aware_navigation.optics import (
    CAMERA_COAXIAL,
    CAMERA_OFFAXIS,
    CONFIGURATIONS,
    LIDAR,
    WaterState,
    channel_response,
)

ALTITUDES = (1.0, 1.5, 2.0, 2.5, 3.0, 4.0)
TURBIDITIES = (0.15, 0.35, 0.60, 0.90, 1.20, 1.60, 2.00)


def build_samples(seed: int, repeats: int = 2) -> list[AvailabilitySample]:
    """Generate development observations from the physics model.

    ``quality`` is observed through the *active* configuration (the off-axis
    camera, the vehicle's default), while availability is recorded for each
    *candidate* configuration. That asymmetry is the point: the manager must
    predict configurations it is not currently using.
    """
    rng = np.random.default_rng(seed)
    samples: list[AvailabilitySample] = []
    for c in TURBIDITIES:
        water = WaterState(c=c)
        for altitude in ALTITUDES:
            for _ in range(repeats):
                observed = channel_response(water, altitude, CAMERA_OFFAXIS, rng=rng)
                for candidate_altitude in ALTITUDES:
                    for candidate in CONFIGURATIONS:
                        result = channel_response(
                            water, candidate_altitude, candidate, rng=rng)
                        samples.append(
                            AvailabilitySample(
                                quality=observed.quality,
                                observed_altitude_m=altitude,
                                candidate_altitude_m=candidate_altitude,
                                configuration=candidate.name,
                                available=result.available,
                            )
                        )
    return samples


@pytest.fixture(scope="module")
def fitted():
    train = build_samples(seed=20_000_001)
    model = AvailabilityModel().fit(train)
    holdout = build_samples(seed=20_000_002)
    return model, train, holdout


# ---------------------------------------------------------------------------
# Fitting and prediction
# ---------------------------------------------------------------------------
def test_predicts_every_configuration(fitted):
    model, _, _ = fitted
    for cfg in CONFIGURATIONS:
        p = model.predict(0.8, 3.0, 2.0, cfg.name)
        assert 0.0 <= p <= 1.0


def test_unfitted_model_refuses_to_predict():
    with pytest.raises(RuntimeError):
        AvailabilityModel().predict(0.5, 3.0, 2.0, "camera_offaxis")


def test_unseen_configuration_is_not_answered_confidently(fitted):
    """A model asked about something it never saw must say 'I don't know',
    not guess with confidence."""
    model, _, _ = fitted
    assert model.predict(0.9, 3.0, 2.0, "sensor_that_does_not_exist") == pytest.approx(0.5)


# ---------------------------------------------------------------------------
# Calibration -- the property that matters more than accuracy
# ---------------------------------------------------------------------------
def test_brier_score_beats_the_base_rate_predictor(fitted):
    model, _, holdout = fitted
    informed = model.brier(holdout)
    base = brier_score(
        [np.mean([s.available for s in holdout])] * len(holdout),
        [s.available for s in holdout],
    )
    assert informed < base, f"model {informed:.4f} no better than base rate {base:.4f}"


def test_calibration_gap_is_small_on_held_back_data(fitted):
    """If the model says 70%, roughly 70% must actually succeed. A
    confident-but-wrong model makes the manager act decisively on bad
    predictions, which is worse than an uncertain one."""
    model, _, holdout = fitted
    assert model.max_calibration_gap(holdout) < 0.25


def test_reliability_bins_cover_the_samples(fitted):
    model, _, holdout = fitted
    rows = model.reliability(holdout, bins=10)
    assert sum(r.count for r in rows) == len(holdout)


# ---------------------------------------------------------------------------
# The physics the model must have learned
# ---------------------------------------------------------------------------
def test_learns_that_descending_helps(fitted):
    """Lower altitude means shorter optical path, so availability must rise."""
    model, _, _ = fitted
    for cfg in (CAMERA_OFFAXIS, LIDAR):
        # Same observation, made at 3 m. Descending vs climbing from there.
        low = model.predict(0.5, 3.0, 1.0, cfg.name)
        high = model.predict(0.5, 3.0, 4.0, cfg.name)
        assert low > high, f"{cfg.name} did not learn the altitude lever"


def test_learns_that_the_laser_outreaches_the_camera(fitted):
    """Published limits are 1-2 / ~3 / 5-6 attenuation lengths. In degraded
    water at survey altitude the ordering must be recovered from data."""
    model, _, _ = fitted
    q, h = 0.35, 3.0
    assert model.predict(q, h, h, LIDAR.name) > model.predict(
        q, h, h, CAMERA_OFFAXIS.name)
    assert model.predict(q, h, h, CAMERA_OFFAXIS.name) >= model.predict(
        q, h, h, CAMERA_COAXIAL.name)


def test_counterfactual_prediction_is_possible_when_the_active_channel_fails(fitted):
    """The manager needs a usable prediction precisely when the current
    configuration is failing. If quality collapsed to zero on failed ticks this
    would be impossible -- which is why quality is an image statistic rather
    than a property of the fix."""
    model, _, _ = fitted
    rng = np.random.default_rng(7)

    # Find the regime where the active channel has failed but the image still
    # carries information. Scanning rather than hardcoding also demonstrates
    # that such a regime exists at all -- if it did not, the manager would only
    # ever learn of a failure once it was already blind.
    informative = [
        (c, r)
        for c in np.arange(0.50, 1.00, 0.02)
        for r in [channel_response(WaterState(c=float(c)), 3.0, CAMERA_OFFAXIS,
                                   rng=rng)]
        if not r.available and r.quality > 0.0
    ]
    assert informative, "no regime where the channel fails but quality survives"

    for _, observed in informative[:5]:
        p = model.predict(observed.quality, 3.0, 1.0, LIDAR.name)
        assert 0.0 <= p <= 1.0


def test_total_whiteout_yields_no_information_and_says_so(fitted):
    """Past a point the camera genuinely sees nothing: backscatter dominates the
    attenuated return, contrast goes negative, and quality is zero. That is the
    honest amount of information available, and the manager is then reduced to
    knowing only that conditions are bad."""
    observed = channel_response(WaterState(c=2.0), 3.0, CAMERA_OFFAXIS,
                                rng=np.random.default_rng(3))
    assert observed.contrast <= 0.0
    assert observed.quality == 0.0


# ---------------------------------------------------------------------------
# Robustness and reproducibility
# ---------------------------------------------------------------------------
def test_separable_data_does_not_diverge():
    """In clear water at low altitude every configuration succeeds. An
    unregularised logistic fit would send weights to infinity."""
    samples = [
        AvailabilitySample(quality=0.95, observed_altitude_m=1.0,
                           candidate_altitude_m=1.0,
                           configuration="camera_offaxis", available=True)
        for _ in range(50)
    ] + [
        AvailabilitySample(quality=0.05, observed_altitude_m=4.0,
                           candidate_altitude_m=4.0,
                           configuration="camera_offaxis", available=False)
        for _ in range(50)
    ]
    model = AvailabilityModel().fit(samples)
    p = model.predict(0.95, 1.0, 1.0, "camera_offaxis")
    assert np.isfinite(p) and 0.0 <= p <= 1.0
    assert p > 0.9


def test_fit_is_deterministic():
    train = build_samples(seed=20_000_003, repeats=2)
    a = AvailabilityModel().fit(train).to_dict()
    b = AvailabilityModel().fit(train).to_dict()
    assert a == b


def test_round_trips_through_the_freeze_record(fitted):
    model, _, holdout = fitted
    restored = AvailabilityModel.from_dict(model.to_dict())
    for s in holdout[:40]:
        args = (s.quality, s.observed_altitude_m, s.candidate_altitude_m,
                s.configuration)
        assert restored.predict(*args) == pytest.approx(model.predict(*args))


def test_model_never_sees_hidden_state():
    """AvailabilitySample must not carry beam attenuation, optical depth, or a
    turbidity index. Training on those would make the model clairvoyant."""
    forbidden = {"c", "tau", "turbidity", "attenuation", "water", "optical_depth"}
    fields = set(AvailabilitySample.__dataclass_fields__)
    assert not (fields & forbidden), f"hidden state in training features: {fields}"
