#!/usr/bin/env python3
"""Render the seabed heightmap Gazebo loads.

Gazebo takes terrain as a greyscale image and stretches it over a given extent.
The relief itself is defined once, in ``uuv_mode_aware_navigation.seabed``, and
this only samples that function onto a grid and writes the picture. The vehicle
node samples the same function for altitude, so what is rendered and what the
altimeter reads are the same surface by construction.

    python3 scripts/make_seabed.py

Writes models/meshes/seabed_height.png. Nothing in the campaign reads it.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from uuv_mode_aware_navigation.seabed import (  # noqa: E402
    EXTENT_M, RELIEF_M, height_at,
)

#: Grid resolution of the seabed mesh, per side.
#:
#: A mesh rather than a <heightmap>. Gazebo's terrain path wants a matched set
#: of diffuse and normal textures and refuses to compile its fragment shader
#: without them, which takes the whole world down; the mesh path is the one the
#: rest of this scene already uses and it simply works. The surface is identical
#: either way because both come from seabed.height_at.
SIDE = 151

#: Metres per texture repeat. Small enough that grain is visible at survey
#: altitude, large enough that the repeat is not obvious from above.
TILE_M = 1.5


def main() -> int:
    out = ROOT / "models" / "meshes"
    out.mkdir(parents=True, exist_ok=True)

    axis = np.linspace(-EXTENT_M, EXTENT_M, SIDE)
    gx, gy = np.meshgrid(axis, axis)
    gz = height_at(gx, gy)

    # Vertex normals from the analytic surface rather than from face averaging:
    # the gradient is available in closed form, so the shading is exact.
    step = axis[1] - axis[0]
    dzdx = (height_at(gx + step, gy) - height_at(gx - step, gy)) / (2 * step)
    dzdy = (height_at(gx, gy + step) - height_at(gx, gy - step)) / (2 * step)
    nx, ny, nz = -dzdx, -dzdy, np.ones_like(gz)
    norm = np.sqrt(nx * nx + ny * ny + nz * nz)

    # Texture coordinates: a planar projection repeating every TILE_M metres.
    # Without these the mesh cannot carry a texture at all, and flat-shaded
    # colour is what makes geometry read as a model rather than as ground.
    lines = ["# generated by scripts/make_seabed.py"]
    for j in range(SIDE):
        for i in range(SIDE):
            lines.append(f"v {gx[j,i]:.4f} {gy[j,i]:.4f} {gz[j,i]:.4f}")
    for j in range(SIDE):
        for i in range(SIDE):
            lines.append(f"vt {gx[j,i]/TILE_M:.4f} {gy[j,i]/TILE_M:.4f}")
    for j in range(SIDE):
        for i in range(SIDE):
            lines.append(f"vn {nx[j,i]/norm[j,i]:.4f} "
                         f"{ny[j,i]/norm[j,i]:.4f} {nz[j,i]/norm[j,i]:.4f}")
    for j in range(SIDE - 1):
        for i in range(SIDE - 1):
            a0 = j * SIDE + i + 1
            b0 = a0 + 1
            c0 = a0 + SIDE
            d0 = c0 + 1
            # Counter-clockwise seen from above, so the front face points UP.
            # The other winding puts the textured side against the sea floor:
            # the surface then renders as an untextured back face from every
            # normal viewpoint, and only looks right if you fly under it.
            for tri in ((a0, d0, c0), (a0, b0, d0)):
                lines.append("f " + " ".join(f"{v}/{v}/{v}" for v in tri))
    (out / "seabed.obj").write_text("\n".join(lines) + "\n")

    lo, hi = float(gz.min()), float(gz.max())
    print(f"wrote {out / 'seabed.obj'}")
    print(f"  {SIDE} x {SIDE} grid over {2*EXTENT_M:.0f} x {2*EXTENT_M:.0f} m "
          f"({(2*EXTENT_M)/(SIDE-1):.2f} m spacing)")
    print(f"  {SIDE*SIDE} vertices, {2*(SIDE-1)**2} faces")
    print(f"  relief {hi-lo:.3f} m peak to trough, declared {RELIEF_M} m")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
