#!/usr/bin/env python3
"""Generate coral, sponge and fish meshes for the demonstrator scene.

A seabed of rocks and grass reads as a quarry floor. What makes it read as a
reef is structure that could only be alive: branching, radial, or streamlined.
None of it can come from SDF primitives, so this writes meshes.

    python3 scripts/make_scenery.py

Everything is drawn from fixed seeds, so the same scenery is produced on every
machine. Nothing in the campaign reads any of it: this is scenery for the
demonstrator, and the study's numbers come from the headless runner which never
loads a world file at all.

Natural colour is handled in the world file rather than here, and is worth a
note. Reef colours look vivid in photographs because photographers carry
lights. At any depth the red end is already gone from the ambient, so the same
coral is a muted brown-grey until the vehicle's lamps reach it and it flushes
back to orange. That is the effect the materials aim for, and it is the same
physics the optical channel of this study depends on.
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "models" / "meshes"


# --------------------------------------------------------------------------
# mesh helpers
# --------------------------------------------------------------------------
class Mesh:
    def __init__(self) -> None:
        self.v: list[np.ndarray] = []
        self.f: list[tuple[int, int, int]] = []

    def add(self, verts, faces) -> None:
        base = len(self.v)
        self.v.extend(verts)
        self.f.extend((a + base, b + base, c + base) for a, b, c in faces)

    def tube(self, p0, p1, r0, r1, sides=7) -> None:
        p0, p1 = np.asarray(p0, float), np.asarray(p1, float)
        axis = p1 - p0
        length = np.linalg.norm(axis)
        if length < 1e-9:
            return
        axis /= length
        tmp = np.array([0.0, 0.0, 1.0]) if abs(axis[2]) < 0.9 else np.array([1.0, 0.0, 0.0])
        u = np.cross(axis, tmp); u /= np.linalg.norm(u)
        w = np.cross(axis, u)
        verts, faces = [], []
        for i in range(sides):
            a = 2 * math.pi * i / sides
            d = math.cos(a) * u + math.sin(a) * w
            verts.append(p0 + d * r0)
            verts.append(p1 + d * r1)
        for i in range(sides):
            a0, b0 = 2 * i, 2 * i + 1
            a1, b1 = (2 * ((i + 1) % sides)), (2 * ((i + 1) % sides) + 1)
            faces += [(a0, b0, b1), (a0, b1, a1)]
        self.add(verts, faces)

    def blob(self, centre, radius, rng, squash=1.0, lumps=0.28) -> None:
        """A lumpy sphere: brain coral, sponge, fish body."""
        rings, seg = 10, 14
        verts = []
        axes = rng.normal(size=(5, 3))
        axes /= np.linalg.norm(axes, axis=1)[:, None]
        phase = rng.uniform(0, 2 * math.pi, 5)
        for i in range(rings + 1):
            th = math.pi * i / rings
            for j in range(seg):
                ph = 2 * math.pi * j / seg
                d = np.array([math.sin(th) * math.cos(ph),
                              math.sin(th) * math.sin(ph),
                              math.cos(th)])
                n = sum(math.sin(d @ ax * 4.0 + p) for ax, p in zip(axes, phase)) / 5.0
                r = radius * (1.0 + lumps * n)
                verts.append(np.array(centre) + d * r * np.array([1, 1, squash]))
        faces = []
        for i in range(rings):
            for j in range(seg):
                a = i * seg + j
                b = i * seg + (j + 1) % seg
                c = (i + 1) * seg + j
                d = (i + 1) * seg + (j + 1) % seg
                faces += [(a, c, d), (a, d, b)]
        self.add(verts, faces)

    def write(self, path: Path) -> None:
        v = np.array(self.v)
        normals = np.zeros_like(v)
        for a, b, c in self.f:
            n = np.cross(v[b] - v[a], v[c] - v[a])
            normals[a] += n; normals[b] += n; normals[c] += n
        lens = np.linalg.norm(normals, axis=1); lens[lens < 1e-12] = 1.0
        normals /= lens[:, None]
        with path.open("w") as fh:
            fh.write("# generated by scripts/make_scenery.py\n")
            for p in v:
                fh.write(f"v {p[0]:.5f} {p[1]:.5f} {p[2]:.5f}\n")
            for n in normals:
                fh.write(f"vn {n[0]:.5f} {n[1]:.5f} {n[2]:.5f}\n")
            for a, b, c in self.f:
                fh.write(f"f {a+1}//{a+1} {b+1}//{b+1} {c+1}//{c+1}\n")


# --------------------------------------------------------------------------
# species
# --------------------------------------------------------------------------
def staghorn(seed: int) -> Mesh:
    """Branching coral. Recursive tubes, thinning as they divide."""
    rng = np.random.default_rng(seed)
    m = Mesh()

    def branch(p, direction, radius, length, depth):
        if depth == 0 or radius < 0.006:
            return
        end = p + direction * length
        m.tube(p, end, radius, radius * 0.62)
        for _ in range(rng.integers(2, 4)):
            d = direction + rng.normal(0, 0.55, 3)
            d[2] = abs(d[2]) + 0.35          # branches reach upward
            d /= np.linalg.norm(d)
            branch(end, d, radius * 0.62, length * rng.uniform(0.6, 0.85), depth - 1)

    for _ in range(rng.integers(2, 4)):
        start = np.array([rng.normal(0, 0.04), rng.normal(0, 0.04), 0.0])
        branch(start, np.array([0, 0, 1.0]), 0.030, 0.13, 4)
    return m


def brain(seed: int) -> Mesh:
    rng = np.random.default_rng(seed)
    m = Mesh()
    m.blob((0, 0, 0.10), 0.17, rng, squash=0.62, lumps=0.20)
    return m


def seafan(seed: int) -> Mesh:
    """A gorgonian: branching, but confined to a plane so it reads as a fan."""
    rng = np.random.default_rng(seed)
    m = Mesh()

    def branch(p, ang, radius, length, depth):
        if depth == 0 or radius < 0.004:
            return
        d = np.array([math.sin(ang) * 0.12, math.sin(ang), math.cos(ang) * 0.6 + 0.5])
        d /= np.linalg.norm(d)
        end = p + d * length
        m.tube(p, end, radius, radius * 0.7, sides=5)
        for s in (-1, 1):
            branch(end, ang + s * rng.uniform(0.25, 0.5),
                   radius * 0.7, length * rng.uniform(0.65, 0.85), depth - 1)

    branch(np.zeros(3), 0.0, 0.022, 0.16, 5)
    return m


def fish(seed: int) -> Mesh:
    """A streamlined body with a forked tail. Read at a metre, not held."""
    rng = np.random.default_rng(seed)
    m = Mesh()
    body = Mesh()
    body.blob((0, 0, 0), 0.055, rng, squash=0.85, lumps=0.05)
    v = np.array(body.v)
    v[:, 0] *= 2.3                    # stretch nose to tail
    v[:, 1] *= 0.55                   # flatten laterally
    m.add(list(v), body.f)
    m.tube((-0.11, 0, 0), (-0.175, 0, 0.055), 0.020, 0.001, sides=4)
    m.tube((-0.11, 0, 0), (-0.175, 0, -0.055), 0.020, 0.001, sides=4)
    m.tube((0.0, 0, 0.035), (0.01, 0, 0.10), 0.016, 0.001, sides=4)
    return m


def wreck(seed: int) -> Mesh:
    """A small broken hull, half buried and open along one side.

    Not a ship model: a hull form with a collapsed section, which at survey
    altitude is what a wreck reads as. It exists because a seabed with one
    man-made object on it has a scale and a story that a field of rocks does
    not, and because a wreck is exactly the kind of target these vehicles are
    sent to look at.
    """
    rng = np.random.default_rng(seed)
    m = Mesh()
    # hull: a long tapered box, listing to one side
    L, W, H = 6.2, 1.7, 1.5
    for i in range(9):
        f = i / 8.0
        taper = 1.0 - 0.65 * (f ** 2)          # narrows toward the bow
        x = -L / 2 + L * f
        m.tube((x, 0, 0), (x + L / 8, 0, 0), W * taper * 0.5, W * (1 - 0.65 * ((f + 0.125) ** 2)) * 0.5, sides=9)
    # keel
    m.tube((-L / 2, 0, -H * 0.45), (L / 2 * 0.9, 0, -H * 0.35), 0.16, 0.10, sides=6)
    # broken ribs where the deck has gone
    for i in range(7):
        x = -L * 0.30 + i * 0.42
        h = rng.uniform(0.5, 1.15)
        m.tube((x, -W * 0.42, 0), (x, -W * 0.30, h), 0.055, 0.035, sides=5)
        if rng.random() < 0.7:
            m.tube((x, W * 0.42, 0), (x, W * 0.28, h * rng.uniform(0.5, 1.0)),
                   0.055, 0.035, sides=5)
    # a stub mast, fallen
    m.tube((L * 0.16, 0, H * 0.30), (L * 0.16 + 2.1, 0.6, 0.15), 0.09, 0.045, sides=6)
    return m


def pipeline(seed: int) -> Mesh:
    """A section of seabed pipeline with a free span and a concrete collar."""
    rng = np.random.default_rng(seed)
    m = Mesh()
    x = -9.0
    while x < 9.0:
        seg = rng.uniform(1.6, 2.8)
        sag = -0.10 if abs(x) < 3.0 else 0.0      # a free span dips
        m.tube((x, 0, sag), (x + seg, 0, sag), 0.22, 0.22, sides=12)
        x += seg
        if rng.random() < 0.35:                    # concrete weight collar
            m.tube((x - 0.12, 0, sag), (x + 0.12, 0, sag), 0.30, 0.30, sides=12)
    return m


def ship(seed: int) -> Mesh:
    """A survey vessel: tapered hull, raised bow, deckhouse, A-frame aft.

    Built as a hull form rather than a stack of boxes, because a box on the
    water reads as a shipping container and this is the asset the whole
    surface-dependent branch of the study depends on. It should look like
    something that could be on station.
    """
    rng = np.random.default_rng(seed)
    m = Mesh()
    L, B = 18.0, 5.0
    # hull: rings from stern to bow, narrowing and rising forward
    prev = None
    for i in range(13):
        f = i / 12.0
        beam = B * (1.0 - 0.80 * f ** 2.4)          # fine entry at the bow
        rise = 0.9 * f ** 2.2                        # sheer
        x = -L / 2 + L * f
        cur = (x, beam / 2.0, rise)
        if prev is not None:
            m.tube((prev[0], 0, prev[2]), (cur[0], 0, cur[2]),
                   prev[1], cur[1], sides=11)
        prev = cur
    # deck line
    m.tube((-L / 2, 0, 1.0), (L / 2 * 0.93, 0, 1.7), B / 2.1, B / 6.0, sides=11)
    # deckhouse, stepped
    m.tube((-2.2, 0, 1.7), (-2.2, 0, 3.6), 1.9, 1.7, sides=4)
    m.tube((-2.6, 0, 3.6), (-2.6, 0, 4.9), 1.4, 1.2, sides=4)
    m.tube((-2.6, 0, 4.9), (-2.6, 0, 7.2), 0.10, 0.06, sides=4)   # mast
    # A-frame over the stern, which is what launches a vehicle
    for s in (-1, 1):
        m.tube((-L / 2 + 0.6, s * 1.9, 1.6), (-L / 2 - 0.9, s * 1.9, 4.4),
               0.13, 0.11, sides=5)
    m.tube((-L / 2 - 0.9, -1.9, 4.4), (-L / 2 - 0.9, 1.9, 4.4), 0.11, 0.11, sides=5)
    return m


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    made = []
    for i in range(3):
        staghorn(700 + i).write(OUT / f"coral_staghorn_{i}.obj"); made.append(f"coral_staghorn_{i}")
    for i in range(2):
        brain(800 + i).write(OUT / f"coral_brain_{i}.obj"); made.append(f"coral_brain_{i}")
    for i in range(2):
        seafan(900 + i).write(OUT / f"coral_fan_{i}.obj"); made.append(f"coral_fan_{i}")
    for i in range(2):
        fish(1000 + i).write(OUT / f"fish_{i}.obj"); made.append(f"fish_{i}")
    wreck(1100).write(OUT / "wreck.obj"); made.append("wreck")
    pipeline(1200).write(OUT / "pipeline.obj"); made.append("pipeline")
    ship(1300).write(OUT / "ship.obj"); made.append("ship")
    print(f"wrote {len(made)} scenery meshes to {OUT}")
    for name in made:
        n = sum(1 for line in (OUT / f"{name}.obj").read_text().splitlines()
                if line.startswith("v "))
        print(f"  {name:22} {n:5} vertices")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
